set_property PACKAGE_PIN L19 [get_ports sys_clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk_i]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_CLK_P]
set_property PACKAGE_PIN J19 [get_ports HDMI_CLK_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D0_P]
set_property PACKAGE_PIN H20 [get_ports HDMI_D0_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D1_P]
set_property PACKAGE_PIN K21 [get_ports HDMI_D1_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D2_P]
set_property PACKAGE_PIN M21 [get_ports HDMI_D2_P]
set_property PACKAGE_PIN AB10 [get_ports uart_rx]
set_property PACKAGE_PIN N19 [get_ports sys_rst]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst]


set_property MARK_DEBUG true [get_nets Vsync]
set_property MARK_DEBUG true [get_nets inPix]
set_property MARK_DEBUG true [get_nets {read_data[1]}]
set_property MARK_DEBUG true [get_nets {read_data[3]}]
set_property MARK_DEBUG true [get_nets {read_data[5]}]
set_property MARK_DEBUG true [get_nets {read_data[8]}]
set_property MARK_DEBUG true [get_nets {read_data[10]}]
set_property MARK_DEBUG true [get_nets {read_data[16]}]
set_property MARK_DEBUG true [get_nets {read_data[21]}]
set_property MARK_DEBUG true [get_nets {read_data[23]}]
set_property MARK_DEBUG true [get_nets {read_data[4]}]
set_property MARK_DEBUG true [get_nets {read_data[7]}]
set_property MARK_DEBUG true [get_nets {read_data[9]}]
set_property MARK_DEBUG true [get_nets {read_data[11]}]
set_property MARK_DEBUG true [get_nets {read_data[15]}]
set_property MARK_DEBUG true [get_nets {read_data[18]}]
set_property MARK_DEBUG true [get_nets {read_data[20]}]
set_property MARK_DEBUG true [get_nets {read_data[0]}]
set_property MARK_DEBUG true [get_nets {read_data[2]}]
set_property MARK_DEBUG true [get_nets {read_data[6]}]
set_property MARK_DEBUG true [get_nets {read_data[12]}]
set_property MARK_DEBUG true [get_nets {read_data[22]}]
set_property MARK_DEBUG true [get_nets {read_data[13]}]
set_property MARK_DEBUG true [get_nets {read_data[14]}]
set_property MARK_DEBUG true [get_nets {read_data[17]}]
set_property MARK_DEBUG true [get_nets {read_data[19]}]

set_property MARK_DEBUG false [get_nets {read_data[25]}]
set_property MARK_DEBUG false [get_nets {read_data[31]}]
set_property MARK_DEBUG false [get_nets {read_data[29]}]
set_property MARK_DEBUG false [get_nets {read_data[26]}]
set_property MARK_DEBUG false [get_nets {read_data[27]}]
set_property MARK_DEBUG false [get_nets {read_data[28]}]
set_property MARK_DEBUG false [get_nets {read_data[30]}]
set_property MARK_DEBUG false [get_nets {read_data[24]}]
set_property MARK_DEBUG true [get_nets req_write]
set_property MARK_DEBUG true [get_nets {uart_data[0]}]
set_property MARK_DEBUG true [get_nets {uart_data[1]}]
set_property MARK_DEBUG true [get_nets {uart_data[2]}]
set_property MARK_DEBUG true [get_nets {uart_data[3]}]
set_property MARK_DEBUG true [get_nets {uart_data[4]}]
set_property MARK_DEBUG true [get_nets {uart_data[5]}]
set_property MARK_DEBUG true [get_nets {uart_data[6]}]
set_property MARK_DEBUG true [get_nets {uart_data[7]}]
set_property MARK_DEBUG true [get_nets ack_write]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[0]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[2]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[4]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[7]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[9]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[10]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[11]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[19]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[14]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[15]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[3]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[6]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[16]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[25]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[8]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[13]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[17]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[22]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[26]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[1]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[5]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[12]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[18]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[20]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[21]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[23]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[24]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_addr[27]}]
set_property MARK_DEBUG true [get_nets ddr_inst/app_en]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_cmd[0]}]
set_property MARK_DEBUG true [get_nets ddr_inst/app_wdf_wren]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[7]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[11]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[15]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[18]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[20]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[22]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[29]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[30]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[0]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[2]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[4]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[9]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[16]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[17]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[28]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[3]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[8]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[12]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[13]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[25]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[27]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[31]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[5]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[1]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[6]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[10]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[14]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[19]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[21]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[26]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[23]}]
set_property MARK_DEBUG true [get_nets {ddr_inst/app_wdf_mask[24]}]
set_property MARK_DEBUG true [get_nets ddr_inst/app_rd_data_valid]
set_property MARK_DEBUG true [get_nets ddr_inst/app_rdy]
set_property MARK_DEBUG true [get_nets ddr_inst/app_wdf_rdy]
set_property MARK_DEBUG true [get_nets ddr_inst/ddrapp_inst/fifo_full]
set_property MARK_DEBUG true [get_nets ddr_inst/ddrapp_inst/app_rd_data_valid]
set_property MARK_DEBUG true [get_nets ddr_inst/ddrapp_inst/fifo_reset]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list ddr_inst/u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/CLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {uart_data[0]} {uart_data[1]} {uart_data[2]} {uart_data[3]} {uart_data[4]} {uart_data[5]} {uart_data[6]} {uart_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 28 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ddr_inst/app_addr[0]} {ddr_inst/app_addr[1]} {ddr_inst/app_addr[2]} {ddr_inst/app_addr[3]} {ddr_inst/app_addr[4]} {ddr_inst/app_addr[5]} {ddr_inst/app_addr[6]} {ddr_inst/app_addr[7]} {ddr_inst/app_addr[8]} {ddr_inst/app_addr[9]} {ddr_inst/app_addr[10]} {ddr_inst/app_addr[11]} {ddr_inst/app_addr[12]} {ddr_inst/app_addr[13]} {ddr_inst/app_addr[14]} {ddr_inst/app_addr[15]} {ddr_inst/app_addr[16]} {ddr_inst/app_addr[17]} {ddr_inst/app_addr[18]} {ddr_inst/app_addr[19]} {ddr_inst/app_addr[20]} {ddr_inst/app_addr[21]} {ddr_inst/app_addr[22]} {ddr_inst/app_addr[23]} {ddr_inst/app_addr[24]} {ddr_inst/app_addr[25]} {ddr_inst/app_addr[26]} {ddr_inst/app_addr[27]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {ddr_inst/app_wdf_mask[0]} {ddr_inst/app_wdf_mask[1]} {ddr_inst/app_wdf_mask[2]} {ddr_inst/app_wdf_mask[3]} {ddr_inst/app_wdf_mask[4]} {ddr_inst/app_wdf_mask[5]} {ddr_inst/app_wdf_mask[6]} {ddr_inst/app_wdf_mask[7]} {ddr_inst/app_wdf_mask[8]} {ddr_inst/app_wdf_mask[9]} {ddr_inst/app_wdf_mask[10]} {ddr_inst/app_wdf_mask[11]} {ddr_inst/app_wdf_mask[12]} {ddr_inst/app_wdf_mask[13]} {ddr_inst/app_wdf_mask[14]} {ddr_inst/app_wdf_mask[15]} {ddr_inst/app_wdf_mask[16]} {ddr_inst/app_wdf_mask[17]} {ddr_inst/app_wdf_mask[18]} {ddr_inst/app_wdf_mask[19]} {ddr_inst/app_wdf_mask[20]} {ddr_inst/app_wdf_mask[21]} {ddr_inst/app_wdf_mask[22]} {ddr_inst/app_wdf_mask[23]} {ddr_inst/app_wdf_mask[24]} {ddr_inst/app_wdf_mask[25]} {ddr_inst/app_wdf_mask[26]} {ddr_inst/app_wdf_mask[27]} {ddr_inst/app_wdf_mask[28]} {ddr_inst/app_wdf_mask[29]} {ddr_inst/app_wdf_mask[30]} {ddr_inst/app_wdf_mask[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {ddr_inst/app_cmd[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list ack_write]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list ddr_inst/app_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list ddr_inst/app_rd_data_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list ddr_inst/app_rdy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list ddr_inst/app_wdf_rdy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list ddr_inst/app_wdf_wren]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list ddr_inst/ddrapp_inst/fifo_full]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list req_write]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list instance_name/inst/clk_hdmi]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 24 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {read_data[0]} {read_data[1]} {read_data[2]} {read_data[3]} {read_data[4]} {read_data[5]} {read_data[6]} {read_data[7]} {read_data[8]} {read_data[9]} {read_data[10]} {read_data[11]} {read_data[12]} {read_data[13]} {read_data[14]} {read_data[15]} {read_data[16]} {read_data[17]} {read_data[18]} {read_data[19]} {read_data[20]} {read_data[21]} {read_data[22]} {read_data[23]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list inPix]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list Vsync]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_hdmi]
