# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w256to32/fifo_w256to32.xci
# IP: The module: 'fifo_w256to32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w256to32/fifo_w256to32.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256to32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w256to32/fifo_w256to32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256to32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w256to32/fifo_w256to32.xci
# IP: The module: 'fifo_w256to32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w256to32/fifo_w256to32.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256to32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w256to32/fifo_w256to32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256to32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
