# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w32to8/fifo_w32to8.xci
# IP: The module: 'fifo_w32to8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w32to8/fifo_w32to8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w32to8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w32to8/fifo_w32to8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w32to8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w32to8/fifo_w32to8.xci
# IP: The module: 'fifo_w32to8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w32to8/fifo_w32to8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w32to8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpga/25_uart_send_pic_to_hdmi/project/project.srcs/sources_1/ip/fifo_w32to8/fifo_w32to8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w32to8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
