
(custom-set-variables
'(verilog-align-ifelse t)
'(verilog-auto-delete-trailing-whitespace t)
'(verilog-auto-inst-param-value t)
'(verilog-auto-inst-vector t)
'(verilog-auto-lineup (quote all))
'(verilog-auto-newline nil)
'(verilog-auto-save-policy nil)
'(verilog-auto-template-warn-unused t)
'(verilog-case-indent 8)
'(verilog-cexp-indent 8)
'(verilog-highlight-grouping-keywords t)
'(verilog-highlight-modules t)
'(verilog-indent-level 8)
'(verilog-indent-level-behavioral 8)
'(verilog-indent-level-declaration 8)
'(verilog-indent-level-module 4)
'(verilog-tab-to-comment t))
