######################################################################
#
# File name : sim_tb_top_wave.do
# Created on: Sun Aug 19 07:30:28 GMT 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
