######################################################################
#
# File name : sim_tb_top_wave.do
# Created on: Fri Aug 17 09:40:17 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
