######################################################################
#
# File name : sim_tb_top_compile.do
# Created on: Fri Aug 17 10:39:21 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../exp/mig_7series_0_ex/imports" \
"../../../../project.srcs/sources_1/ip/ila_uart/ila_uart_sim_netlist.v" \
"../../../../project.srcs/sources_1/ip/ila_1/sim/ila_1.v" \
"../../../../project.srcs/sources_1/ip/mig_7series_1/mig_7series_1_sim_netlist.v" \
"../../../../project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_sim_netlist.v" \
"../../../../project.srcs/sources_1/new/bit8to256.v" \
"../../../../project.srcs/sources_1/new/top.v" \
"../../../../project.srcs/sources_1/new/uart_rx_path.v" \
"../../../../project.srcs/sources_1/new/uart_tx_path.v" \
"../../../../project.srcs/sources_1/new/uartddr.v" \
"../../../../../exp/mig_7series_0_ex/imports/wiredly.v" \

C:\\modeltech64_10.5\\win64\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../../exp/mig_7series_0_ex/imports" \
"../../../../../exp/mig_7series_0_ex/imports/ddr3_model.sv" \

C:\\modeltech64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../exp/mig_7series_0_ex/imports" \
"../../../../project.srcs/sim_1/new/tb_top.v" \

# compile glbl module
C:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

