# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/fpga/28_sobel/sobel/sobel.srcs/sources_1/ip/pic_320x240_rgb565/pic_320x240_rgb565.xci
# IP: The module: 'pic_320x240_rgb565' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga/28_sobel/sobel/sobel.srcs/sources_1/ip/pic_320x240_rgb565/pic_320x240_rgb565_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pic_320x240_rgb565'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/fpga/28_sobel/sobel/sobel.srcs/sources_1/ip/pic_320x240_rgb565/pic_320x240_rgb565.xci
# IP: The module: 'pic_320x240_rgb565' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga/28_sobel/sobel/sobel.srcs/sources_1/ip/pic_320x240_rgb565/pic_320x240_rgb565_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pic_320x240_rgb565'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
