# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# IP: ip/mig_7series_1/mig_7series_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_1 || ORIG_REF_NAME==mig_7series_1} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
