######################################################################
##
## Filename: sim_tb_top.udo
## Created on: Fri Aug 10 10:01:10 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
