# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/fpga/24_ddr3_vivado/ddr_mig_ex/imports/example_top.xdc

# IP: ip/ddr_mig/ddr_mig.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_mig || ORIG_REF_NAME==ddr_mig} -quiet] -quiet

# XDC: ip/ddr_mig/ddr_mig/user_design/constraints/ddr_mig.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_mig || ORIG_REF_NAME==ddr_mig} -quiet] -quiet

# XDC: ip/ddr_mig/ddr_mig/user_design/constraints/ddr_mig_ooc.xdc
