# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/fpga/25_uart_send_pic_to_hdmi/Test/mig_7series_2_ex/imports/example_top.xdc

# IP: ip/mig_7series_2/mig_7series_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_2 || ORIG_REF_NAME==mig_7series_2} -quiet] -quiet
