# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# IP: ip/HDMI_FPGA_ML_A7_0/HDMI_FPGA_ML_A7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_FPGA_ML_A7_0 || ORIG_REF_NAME==HDMI_FPGA_ML_A7_0} -quiet] -quiet
