set_property PACKAGE_PIN L19 [get_ports clk_50m]

set_property PACKAGE_PIN K18 [get_ports HDMI_CLK_P]
set_property PACKAGE_PIN M18 [get_ports HDMI_D0_P]
set_property PACKAGE_PIN N20 [get_ports HDMI_D1_P]
set_property PACKAGE_PIN N22 [get_ports HDMI_D2_P]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50m]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_CLK_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D0_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D1_P]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D2_P]
