######################################################################
#
# File name : sim_tb_top_compile.do
# Created on: Sat Aug 11 16:41:28 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modelsim\\win64\\vlib modelsim_lib/work
C:\\modelsim\\win64\\vlib modelsim_lib/msim

C:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../ddr_mig_ex/imports" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/clocking/mig_7series_v4_1_clk_ibuf.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/clocking/mig_7series_v4_1_infrastructure.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/clocking/mig_7series_v4_1_iodelay_ctrl.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/clocking/mig_7series_v4_1_tempmon.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_arb_mux.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_arb_row_col.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_arb_select.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_bank_cntrl.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_bank_common.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_bank_compare.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_bank_mach.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_bank_queue.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_bank_state.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_col_mach.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_mc.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_rank_cntrl.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_rank_common.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_rank_mach.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/controller/mig_7series_v4_1_round_robin_arb.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ecc/mig_7series_v4_1_ecc_buf.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ecc/mig_7series_v4_1_ecc_dec_fix.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ecc/mig_7series_v4_1_ecc_gen.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ecc/mig_7series_v4_1_ecc_merge_enc.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ecc/mig_7series_v4_1_fi_xor.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ip_top/mig_7series_v4_1_memc_ui_top_std.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ip_top/mig_7series_v4_1_mem_intfc.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_byte_group_io.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_byte_lane.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_calib_top.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_if_post_fifo.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_mc_phy.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_mc_phy_wrapper.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_of_pre_fifo.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_4lanes.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ck_addr_cmd_delay.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal_hr.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_init.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_cntlr.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_data.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_edge.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_lim.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_mux.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_po_cntlr.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_samp.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_oclkdelay_cal.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_prbs_rdlvl.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_rdlvl.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_tempmon.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_top.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrcal.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl_off_delay.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_prbs_gen.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_ddr_skip_calib_tap.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_poc_cc.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_poc_edge_store.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_poc_meta.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_poc_pd.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_poc_tap_base.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/phy/mig_7series_v4_1_poc_top.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ui/mig_7series_v4_1_ui_cmd.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ui/mig_7series_v4_1_ui_rd_data.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ui/mig_7series_v4_1_ui_top.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ui/mig_7series_v4_1_ui_wr_data.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ddr_mig_mig_sim.v" \
"c:/Users/fei_l/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12088-DESKTOP-B3SJCBK/coregen/ddr_mig/ddr_mig/user_design/rtl/ddr_mig.v" \
"../../../../../ddr_mig_ex/imports/example_top.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_afifo.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_cmd_gen.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_cmd_prbs_gen.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_data_prbs_gen.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_init_mem_pattern_ctr.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_memc_flow_vcontrol.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_memc_traffic_gen.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_rd_data_gen.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_read_data_path.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_read_posted_fifo.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_s7ven_data_gen.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_tg_prbs_gen.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_tg_status.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_traffic_gen_top.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_vio_init_pattern_bram.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_wr_data_gen.v" \
"../../../../../ddr_mig_ex/imports/mig_7series_v4_1_write_data_path.v" \
"../../../../../ddr_mig_ex/imports/wiredly.v" \

C:\\modelsim\\win64\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../../ddr_mig_ex/imports" \
"../../../../../ddr_mig_ex/imports/ddr3_model.sv" \

C:\\modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../ddr_mig_ex/imports" \
"../../../../../ddr_mig_ex/imports/sim_tb_top.v" \

# compile glbl module
C:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

